export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <>    
      <body className="dark:bg-slate-900 bg-emerald-50">{children}</body>
    </>
  )
}
