import { ReduxProvider } from "../../lib/rtk/ReduxProvider";
import "./globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="enff">
      <ReduxProvider>
        {children}
      </ReduxProvider>
    </html>
  )
}
