import { Toaster } from "react-hot-toast";
import { NextProviders } from "../../lib/providers/sessionProvider";
import { ReduxProvider } from "../../lib/rtk/ReduxProvider";
import "./globals.css";
import { ToasterProvider } from "../../lib/providers/toasterProvider";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  return (
    <html lang="enff">
      <NextProviders>
        <ReduxProvider>
          <ToasterProvider />
          {children}
          <ToasterProvider />
        </ReduxProvider>
      </NextProviders>
    </html>
  )
}
