import { Inter } from "next/font/google";
import WrapperContainer from "@/components/front/layout/WrapperContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body className="dark:bg-slate-900  bg-white">
      <WrapperContainer>
        {children}
      </WrapperContainer>
    </body>
  );
}
